config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#new'

  resources :gossips 
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user 
    validates :content, length: { maximum: 250 }
end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :gossips
    validates :user_name, presence: true, uniqueness: true
    has_secure_password
    validates :password_digest, length: { minimum: 6 }, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please"}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include SessionsHelper

    before_action :only_signed_in

    def only_signed_in
        if logged_in?
            redirect_to "/sessions/new", danger: "Vous n'avez pas le droit d'acceder a cette page sans etre connecte"
        end
    end


add_flash_types :success, :danger
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

    before_action :set_gossip, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user, only: [:edit, :update, :destroy]


    def index 
        @gossip = Gossip.all 
    end

    def show
        @gossip = Gossip.find(params[:id])
    end

    def new
        @gossip = Gossip.new
    end
    
    def create
                
        @gossip = Gossip.new(gossip_params)
        @gossip.user = User.find_by(id: current_user.id)

        if @gossip.save
            redirect_to gossips_path
        else
            render :new
        end
    end

    
    def edit
        @gossip = Gossip.find(params[:id])
    end
    
    def update
        @gossip = Gossip.find(params[:id])
            gossip_params = params.require(:gossip).permit(:body, :content)
                @gossip.update(gossip_params)
                    redirect_to gossips_path
    end
    
    def destroy
        @gossip = Gossip.find(params[:id])
            @gossip.destroy
                redirect_to gossips_path
    end


    end

    private

	def gossip_params
		return params.require(:gossip).permit(:content)
    end
    
    def set_gossip
        @gossip = Gossip.find(params[:id])
    end

    def authenticate_user
		unless current_user.id == @gossip.user.id
		  flash[:danger] = "Restricted Area"
		  redirect_to gossips_path
		end
	end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :only_signed_in, only: [:new, :create]

def new 

end

def create
    user_params = params.require(:user)
    @user = User.find_by(email: user_params[:email])

    if @user && @user.authenticate(user_params[:password])
        session[:user_id] = @user.id
        redirect_to gossips_path, flash: {success: "Welcome #{@user.user_name}!" }

    else 
        redirect_to new_session_path
        
    end
end

def destroy
    session.delete(:user_id)
    redirect_to gossips_path
end

def user_params
    @user = User.find(params[:id])
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :only_signed_in, only: [:new, :create]

    def index
    @user = User.all
    end

    def show
    @user = User.find(params[:id])
    end

    def new
    @user = User.new
    end

    def create
        user_params = params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
        @user = User.new(user_params)

        if @user.valid?
        @user.save
        redirect_to gossips_path, success: "User created!"

        else
        render :new
    
        end

    end

    private

	def user_params
		return params.require(:user).permit(:user_name, :email, :password_digest )
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user

        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def logged_in?
        session[:user_id].nil?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<center>

<%= form_with model: @gossip, class: "nifty_form" do |f| %>
<%= f.text_area :content, size: "60x12" %> </br>
  <%= f.submit "Edit" %>
<% end %>

</center>

app/views/gossips/index.html.erb
<html>
<head>
  <title>The Gossip Project</title>
</head>
<body>
<center>
<div class="card-columns'">

<% @gossip.each_with_index do |gossip, index| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= gossip.user.user_name%> </h5>
    <h5 class="card-text">" <%= gossip.content %> "</h5>
    <a class="card-link" <%= link_to "SHOW ME THE GOSSIP", gossip_path(gossip.id)%></a>
  </div>
</div>
</div>
<%  end %>

</center>



</body>
</html>

app/views/gossips/new.html.erb
<center> </h3>

</br> 

<%= form_with model: @gossip, class: "nifty_form" do |f| %>
<%= f.text_area :content, size: "60x12" %> </br>
  <%= f.submit "Post your gossip" %>
<% end %>

</br>

<a href ='/gossips/'> Click here to return to the index ! </a> </center>

app/views/gossips/show.html.erb
<center>

<div class="card-columns'">

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @gossip.user.user_name%> </h5>
    <h5 class="card-text">" <%= @gossip.content %> " </h5>
  </div>
</div>
</div>

  <a class="btn btn-primary mx-3" href ='/gossips/'> Return to the index </a>
<a class="btn btn-dark mx-3" <%= link_to "Edit Gossip", edit_gossip_path(@gossip.id)%></a>
<a class="btn btn-danger mx-3" data-confirm="Are you sure?" data-method="DELETE" <%= link_to "Delete Gossip", gossip_path(@gossip.id)%></a>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipGhost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
 <link href="https://fonts.googleapis.com/css?family=Lobster|Merriweather&display=swap" rel="stylesheet"> 
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/gossips/">Gossip Ghost V.8.7</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/gossips/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/gossips/new">Create a New Gossip</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Create a New Account <span class="sr-only">(current)</span></a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="/users">Ghosts List</a>
        </li>
        <ul class="nav-item navbar-right">
      <% if logged_in? %>
                                    <li>    <%= link_to "Login", new_session_path, class: 'btn btn-success' %>  </li>
                                <% else %>
                                    <li>    <%= link_to "Log out", session_path(session.id), method: :delete, class: 'btn btn-danger' %>  </li>
                                <%end%>
      
    </ul>
    </div>
  </nav>


<header class="bg-primary text-white">
    <div class="container text-center">
      <h1>Welcome to Gossip Ghost</h1>
      <p class="lead">Spread false informations faster than STDs !</p>
    </div>


                              

</header>

    <% if flash[:success] %>
      <div class= "alert alert-success">
        <% flash[:success] %>
        </div>
      <% end %>

      <% if flash[:danger] %>
      <div class= "alert alert-success">
        <% flash[:danger] %>
        </div>
      <% end %>

    <%= yield %>




    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<center>

<% @user.each_with_index do |user, index| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= user.user_name%> </h5>
    
    <a class="card-link" <%= link_to "SHOW ME THE USER", user_path(user.id)%></a>
  </div>
</div>
<%  end %>

</center>

app/views/users/new.html.erb
<center>

<div class="panel panel-default">
    <div class="panel-heading">Create an account</div>
    <div class="panel-body">

<%= form_for @user, class: "form-horizontal" do |f| %>

<div class="form-group">
<%= f.label :user_name, "Username", class: 'col-md4 control-label' %>
<div class="col-md-6">
  <%= f.text_field :user_name, class: 'form-control' %>
 </div>
  </div>

  <div class="form-group">
<%= f.label :email, "Email", class: 'col-md4 control-label' %>
<div class="col-md-6">
  <%= f.email_field :email, class: 'form-control' %>
 </div>
  </div>

  <div class="form-group">
<%= f.label :password, "Password", class: 'col-md4 control-label' %>
<div class="col-md-6">
  <%= f.password_field :password, class: 'form-control' %>
 </div>
  </div>

    <div class="form-group">
<%= f.label :password_confirmation, "Confirm Password", class: 'col-md4 control-label' %>
<div class="col-md-6">
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  </div>

  <div class="form-group">
  <div class="col-md-6 col-md-offset-4">
  <button type="submit" class="btn btn-primary">Submit</button>
  </div>
  </div>
<% end %>



<a href ='/gossips/'> Click here to return to the index ! </a> 

</center>

app/views/users/show.html.erb
<center>
<div class="card-columns'">

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @user.user_name %> </h5>
    <h5 class="card-text">Email: <%= @user.email %> </h5>
  </div>
</div>
</div>

</center>